### ISSUE TITLE
News results maximum only 15

### ISSUE THREAD

**Issue by thomas6382** [goferito/node-bing-api#13]
I am not able to generate more than 15 news results. I have tried with the top parameter at 50 or without the top parameter. I have also tried with the composite search but I can only get 15 news results maximum.  The others options parameters are working and it is not a problem of keyword to be too specific as I am using very general term. Thanks

**Comment by goferito** [comment]
I've just checked, in the bing docs, that the $top parameter: "Specifies the number of results to return. The default is 50 for Web, Image, and Video searches, 15 for News."

So yes, they only allow a max of 15 news results per query.
