### ISSUE TITLE
Feature Request: RelatedSearch and SpellingSuggestion

### ISSUE THREAD

**Issue by aqibsaeed** [goferito/node-bing-api#15]
Is there any method to perform SpellingSuggestion or  RelatedSearch using this library? if not do you have any plan to implement it?

**Comment by goferito** [comment]
I have just added the feature. Star the repo if you feel satisfied. Stars make developers happy :smile: 
Also let me know if there is any problem.

Cheers!

**Comment by aqibsaeed** [comment]
You rock man :+1: Thanks a lot for implementing this.
