### ISSUE TITLE
Update to V5

### ISSUE THREAD

**Issue by LouisLoode** [goferito/node-bing-api#24]
Hi,
I received a mail from Microsoft, apparently, there is a new version of the API how incoming. Do you provide to update this package ?

Cordially

**Comment by franciscofsales** [comment]
I updated on my fork and its compatible with V5. Some stuff might not be 100% but it should be more then enough.

https://github.com/franciscofsales/node-bing-api

**Comment by franciscofsales** [comment]
@goferito would you consider merging? Please if you get the time have a look, I had to change a lot of stuff, including tests.

**Comment by goferito** [comment]
@franciscofsales could you make a pr?
