### ISSUE TITLE
freshness

### ISSUE THREAD

**Issue by xauxatz** [goferito/node-bing-api#28]
Hi - does node-bing-api support the freshness parameter?

**Comment by goferito** [comment]
I think it should

**Comment by xauxatz** [comment]
In fact I verified the request in my debugger and it does not take "freshness" into account.
What is worse, it doesn't take "skip" (offset) into account either...
It is simply not build into the search string

**Comment by chovy** [comment]
I'm finding same things -- none of these are supported. Part of the problem with rewriting the api interface 

```
        cc: 'US',
        freshness: 'Day',
        setLang: 'EN'
```

**Comment by goferito** [comment]
Ok, I'll look into it this week

**Comment by chovy** [comment]
for now you can get around it by doing this:

```
      bing.news(`javascript&freshness=Day&setLang=EN&cc=US`, {
        top: this.count,
        skip: this.skip
      }, (err, res, body) => {
        if (err) return reject(err);
        resolve(body);
      })

```

instead of mappiing your custom option names to legit ones you should just take what we give you and turn them into key=value pairs in the query string.

**Comment by anthonyettinger** [comment]
any luck on this?

**Comment by chovy** [comment]
submitted a pr:

https://github.com/goferito/node-bing-api/pull/32

**Comment by goferito** [comment]
Ok, I have accepted the PR and also refactored the code. Sorry it took so long, my account key was not valid any more and microsoft was failing when requesting a new one. I have merged the changes. I publish the new version. Let me know if everything is cool.

Btw, I'm planning to update the code to ES6 for the v4. As a tiny survey... would you find any inconvenience with that?

**Comment by anthonyettinger** [comment]
i'm already using es7 with --harmony-async-await flag so that's fine with me. I would avoid using babel on the server side though.

**Comment by goferito** [comment]
I would only use ES6 features supported on the stable version (6.9.5)

**Comment by goferito** [comment]
You can close this issue to confirm your satisfaction with the solution. An start on the repo would be also nice. Stars make developers happy :star: :smile:

**Comment by xauxatz** [comment]
Thanks :-)
