### ISSUE TITLE
getting unexpected quota errors

### ISSUE THREAD

**Issue by chovy** [goferito/node-bing-api#34]
I check my dashboard and it says I have over 1000 api calls left.

But I keep getting these messages:

```
{ "statusCode": 403, "message": "Out of call volume quota. Quota will be replenished in 22.14:18:12." }
```

**Comment by goferito** [comment]
The library doesn't manipulate the returned errors at all. That error is coming directly from the cognitive servers. 
You might be doing to many requests per minute, but you still have a 1000 left for the month. That's just a possibility. You should be asking that to them. I don't think that has nothing to do with this library.

**Comment by anthonyettinger** [comment]
Yeah, I figured you might know. Not sure what format this date is in: `22.14:18:12`

**Comment by goferito** [comment]
Sorry man, I'm afraid I can't help with that. Have you discovered what happened?

**Comment by chovy** [comment]
Nope. My dashboard says I still have several thousand requests but I am blocked from their api.
I will probably have to open a support ticket.
