### ISSUE TITLE
v7 Supported?

### ISSUE THREAD

**Issue by mtrivera** [goferito/node-bing-api#44]
I registered for Bing Search API and I have 28 days remaining. But I get this message when I try to test it. I've tried both keys to no success.

`"{ \"statusCode\": 401, \"message\": \"Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription.\" }"`

**Comment by chovy** [comment]
I still get resource not found.

CognitiveServices now forces you to use your own endpoint.

I'm not sure how to pass it. The endpoints for /news/search is what i want.

I'm trying this:

```
 this.client = require('node-bing-api')({ accKey: opts.apiKey, rootUri: opts.rootUri });
```

apiKey is my api key and rootUri is `BING_ENDPOINT=https://puump.cognitiveservices.azure.com/bing/v7.0`
